### ISSUE TITLE
Does the code base work with the free version of mujuco?

### ISSUE THREAD

**Issue by snailrowen1337** [huangwl18/geometry-dex#1]
Thanks for releasing this! I was wondering: does the code base work with the free version of mujuco?

**Comment by huangwl18** [comment]
Thanks for the interest in the project. The legacy versions of MuJoCo, including the one used in this project, now come with [a free license](https://roboti.us/license.html). We have not tested with the DeepMind-owned version of MuJoCo (>= 2.1.0), but it likely would work the same. Feel free to try it out!
